---
apiVersion: batch/v1
kind: Job
metadata:
  name: joinchannel
spec:
  backoffLimit: 1
  template:
    metadata:
      name: joinchannel
    spec:
      restartPolicy: "Never"
      volumes:
      - name: sharedvolume
        persistentVolumeClaim:
          claimName: shared-pvc
      containers:
      - name: joinchannel1
        image: hyperledger/fabric-peer:1.4.0
        imagePullPolicy: Always
        command: ["sh", "-c", "peer channel fetch newest -o ${ORDERER_URL} -c ${CHANNEL_NAME} && peer channel join -b ${CHANNEL_NAME}_newest.block "]
        env:
        - name: CHANNEL_NAME
          value: mymarketchannel
        - name: CORE_PEER_NETWORKID
          value: dev
        - name: ORDERER_URL
          value: mymarket-orderer:31010
        - name: CORE_PEER_ADDRESS
          value: store1peer0:30110
        - name: CORE_PEER_LOCALMSPID
          value: Store1MSP
        - name: CORE_PEER_MSPID
          value: Store1MSP
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/store1.mymarket.com/users/Admin@store1.mymarket.com/msp
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
      - name: joinchannel2
        image: hyperledger/fabric-peer:1.4.0
        imagePullPolicy: Always
        command: ["sh", "-c", "peer channel fetch newest -o ${ORDERER_URL} -c ${CHANNEL_NAME} && peer channel join -b ${CHANNEL_NAME}_newest.block "]
        env:
        - name: CHANNEL_NAME
          value: mymarketchannel
        - name: CORE_PEER_NETWORKID
          value: dev
        - name: ORDERER_URL
          value: mymarket-orderer:31010
        - name: CORE_PEER_ADDRESS
          value: store1peer1:30120
        - name: CORE_PEER_LOCALMSPID
          value: Store1MSP
        - name: CORE_PEER_MSPID
          value: Store1MSP
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/store1.mymarket.com/users/Admin@store1.mymarket.com/msp
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
      - name: joinchannel3
        image: hyperledger/fabric-peer:1.4.0
        imagePullPolicy: Always
        command: ["sh", "-c", "peer channel fetch newest -o ${ORDERER_URL} -c ${CHANNEL_NAME} && peer channel join -b ${CHANNEL_NAME}_newest.block "]
        env:
        - name: CHANNEL_NAME
          value: mymarketchannel
        - name: CORE_PEER_NETWORKID
          value: dev
        - name: ORDERER_URL
          value: mymarket-orderer:31010
        - name: CORE_PEER_ADDRESS
          value: store2peer0:30210
        - name: CORE_PEER_LOCALMSPID
          value: Store2MSP
        - name: CORE_PEER_MSPID
          value: Store2MSP
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/store2.mymarket.com/users/Admin@store2.mymarket.com/msp
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
      - name: joinchannel4
        image: hyperledger/fabric-peer:1.4.0
        imagePullPolicy: Always
        command: ["sh", "-c", "peer channel fetch newest -o ${ORDERER_URL} -c ${CHANNEL_NAME} && peer channel join -b ${CHANNEL_NAME}_newest.block "]
        env:
        - name: CHANNEL_NAME
          value: mymarketchannel
        - name: CORE_PEER_NETWORKID
          value: dev
        - name: ORDERER_URL
          value: mymarket-orderer:31010
        - name: CORE_PEER_ADDRESS
          value: store2peer1:30220
        - name: CORE_PEER_LOCALMSPID
          value: Store2MSP
        - name: CORE_PEER_MSPID
          value: Store2MSP
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/store2.mymarket.com/users/Admin@store2.mymarket.com/msp
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: sharedvolume
