# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # MymarketOrderer
  # ---------------------------------------------------------------------------
  - Name: MymarketHeadquater
    Domain: mymarket.com
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # Store1
  # ---------------------------------------------------------------------------
  - Name: Store1 
    Domain: store1.mymarket.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
  # ---------------------------------------------------------------------------
  # Store2 
  # ---------------------------------------------------------------------------
  - Name: Store2
    Domain: store2.mymarket.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
